# Travis CI configuration file for asgineer
# Validate this at http://lint.travis-ci.org/

language: python

branches:
  only:
    - master

matrix:
    include:
        - python: "3.7"
          env: TEST_STYLE_AND_DOCS=1
        - python: "3.6"
          env: ASGI_SERVER=mock
        - python: "3.7"
          env: ASGI_SERVER=mock
        - python: "3.8"
          env: ASGI_SERVER=mock
        - python: "3.7"
          env: ASGI_SERVER=uvicorn
        #- python: "3.7"  -> Hypercorn's behavior does not work with our test mechanics
        #  env: ASGI_SERVER=hypercorn
        - python: "3.7"
          env: ASGI_SERVER=daphne

before_install:
    - SRC_DIR=$(pwd);

install:
    - cd ${SRC_DIR};
    - if [ "${TEST_STYLE_AND_DOCS}" == "1" ]; then
        pip install -U black pyflakes sphinx;
      else
        pip install -U pytest pytest-cov requests websockets;
        python setup.py install;
      fi;
    - if [ "${ASGI_SERVER}" == "uvicorn" ]; then
        pip install -U uvicorn;
      fi;
    - if [ "${ASGI_SERVER}" == "hypercorn" ]; then
        pip install -U hypercorn;
      fi;
    - if [ "${ASGI_SERVER}" == "daphne" ]; then
        pip install -U daphne;
      fi;

script:
    - cd ${SRC_DIR};
    - python -c "import sys; print(sys.version, '\n', sys.prefix)";
    - if [ "${TEST_STYLE_AND_DOCS}" == "1" ]; then
        black --check .;
        pyflakes .;
        sphinx-build docs docs/_build;
      else
        cd tests;
        PYTHONPATH=${SRC_DIR} pytest -v --cov=asgineer --cov-report=term-missing .;
      fi;

after_success:
    - echo SUCCESS!

after_failure:
    - echo FAIL!
