# Travis CI configuration file for asgish
# Validate this at http://lint.travis-ci.org/

language: python

# use container-based infrastructure
# sudo : false

# Trick to get 3.7 working for now
# https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-405506964
dist: xenial
sudo: true

branches:
  only:
    - master

matrix:
    include:
        - python: "3.6"
          env: TEST_STYLE=1
        - python: "3.6"
          env: ASGISH_SERVER=uvicorn
        - python: "3.7"
          env: ASGISH_SERVER=uvicorn
        - python: "3.7"
          env: ASGISH_SERVER=hypercorn
        - python: "3.7"
          env: ASGISH_SERVER=daphne

before_install:
    - SRC_DIR=$(pwd);

install:
    - cd ${SRC_DIR};
    - if [ "${TEST_STYLE}" == "1" ]; then
        pip install black pyflakes;
      else
        pip install pytest pytest-cov requests autobahn;
        python setup.py install;
      fi;
    - if [ "${ASGISH_SERVER}" == "uvicorn" ]; then
        pip install uvicorn;
      fi;
    - if [ "${ASGISH_SERVER}" == "hypercorn" ]; then
        pip install hypercorn;
      fi;
    - if [ "${ASGISH_SERVER}" == "daphne" ]; then
        pip install daphne;
      fi;

script:
    - cd ${SRC_DIR};
    - python -c "import sys; print(sys.version, '\n', sys.prefix)";
    - if [ "${TEST_STYLE}" == "1" ]; then
        black --check .;
        pyflakes .;
      else
        pytest -v .;
      fi;

after_success:
    - echo SUCCESS!

after_failure:
    - echo FAIL!
